import { mkdir, readdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import type { AgentConfig } from "./agent-config.js";
import { pathExists, hashContent } from "./fs-utils.js";
import type { ManagedEntry } from "./manifest.js";

// Compiles the canonical .agents/ source into per-tool views. Everything here is
// deterministic (no timestamps), so an unchanged source produces byte-identical
// output — which is what makes manifest hash-based drift detection work.

const GENERATED_BANNER =
  "<!-- Generated by `saasaloy sync` from .agents/*.md — do not edit; edit the fragments instead. -->";

export interface SyncResult {
  managed: Record<string, ManagedEntry>;
  links: Record<string, string>;
  fragmentCount: number;
  skillCount: number;
}

interface Fragment {
  name: string;
  content: string;
}

/** Read top-level `*.md` fragments from the source dir, sorted by filename. */
async function readFragments(sourceDir: string): Promise<Fragment[]> {
  if (!(await pathExists(sourceDir))) return [];
  const entries = await readdir(sourceDir, { withFileTypes: true });
  const names = entries
    .filter((e) => e.isFile() && e.name.endsWith(".md"))
    .map((e) => e.name)
    .sort();
  const fragments: Fragment[] = [];
  for (const name of names) {
    const content = await readFile(join(sourceDir, name), "utf8");
    fragments.push({ name, content: content.trimEnd() });
  }
  return fragments;
}

/** The literal concatenation Codex/Antigravity read (banner + fragments). */
function buildAgentsContent(fragments: Fragment[]): string {
  const body = fragments.map((f) => f.content).join("\n\n");
  return `${GENERATED_BANNER}\n\n${body}\n`;
}

/** Discover skill folder names under `<source>/skills`. */
async function readSkillNames(skillsDir: string): Promise<string[]> {
  if (!(await pathExists(skillsDir))) return [];
  const entries = await readdir(skillsDir, { withFileTypes: true });
  return entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
}

/**
 * Point `<targetDir>/<skill>` at each `<source>/skills/<skill>` via symlink, and
 * remove stale symlinks that no longer correspond to a source skill. Links are
 * git-ignored and recreated per-OS, so clobbering/refreshing them is always safe.
 */
async function syncSkillLinks(
  root: string,
  sourceSkillsAbs: string,
  skillNames: string[],
  targetDir: string,
): Promise<Record<string, string>> {
  const links: Record<string, string> = {};
  const targetAbs = join(root, targetDir);
  await mkdir(targetAbs, { recursive: true });

  const wanted = new Set(skillNames);

  // Drop stale symlinks first.
  const existing = await readdir(targetAbs, { withFileTypes: true });
  for (const entry of existing) {
    if (entry.isSymbolicLink() && !wanted.has(entry.name)) {
      await rm(join(targetAbs, entry.name), { force: true });
    }
  }

  for (const name of skillNames) {
    const linkPath = join(targetAbs, name);
    const sourcePath = join(sourceSkillsAbs, name);
    await rm(linkPath, { recursive: true, force: true });
    if (process.platform === "win32") {
      // Junctions need an absolute target and only work for directories.
      await symlink(sourcePath, linkPath, "junction");
    } else {
      await symlink(relative(dirname(linkPath), sourcePath), linkPath, "dir");
    }
    links[toPosix(relative(root, linkPath))] = toPosix(relative(root, sourcePath));
  }
  return links;
}

/** Normalize path separators so the manifest is stable across OSes. */
function toPosix(p: string): string {
  return p.split("\\").join("/");
}

export async function compileAgentViews(root: string, config: AgentConfig): Promise<SyncResult> {
  const sourceAbs = join(root, config.source);
  const fragments = await readFragments(sourceAbs);
  const agentsContent = buildAgentsContent(fragments);

  const managed: Record<string, ManagedEntry> = {};

  for (const target of config.concat) {
    const content =
      target.style === "import" ? `@${target.importFrom ?? "AGENTS.md"}\n` : agentsContent;
    const outPath = join(root, target.path);
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, content, "utf8");
    managed[toPosix(target.path)] = { source: "agent-compile", hash: hashContent(content) };
  }

  const sourceSkillsAbs = join(sourceAbs, "skills");
  const skillNames = await readSkillNames(sourceSkillsAbs);
  let links: Record<string, string> = {};
  for (const target of config.skills) {
    const targetLinks = await syncSkillLinks(root, sourceSkillsAbs, skillNames, target.dir);
    links = { ...links, ...targetLinks };
  }

  return {
    managed,
    links,
    fragmentCount: fragments.length,
    skillCount: skillNames.length,
  };
}
