import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, posix } from "node:path";
import { pathExists, resolveWithinRoot } from "./fs-utils.js";

// `apps/api/.dev.vars.example` — the checked-in template a developer copies to
// `.dev.vars` before `wrangler dev`. The base's `_gitignore` has carved out an
// exception for this exact filename since the template shipped, and until #98 nothing
// ever wrote it: every module printed its env vars into the `add` transcript, where
// they scrolled away. `add` now generates the file from the descriptors' own `envVars`
// maps, so the record of what the project needs lives in the project.
//
// Two rules keep the regeneration safe:
//
//   1. A value already in the file wins. The file is checked in, so a team edits it,
//      and `saasaloy add` must never revert that edit.
//   2. Nothing is ever removed. `saasaloy remove` owns deletions; an `add` that dropped
//      a key would silently break a second module that reads the same variable.

export const DEV_VARS_EXAMPLE = ".dev.vars.example";

/** The alias whose workspace holds the Worker that reads `.dev.vars`. */
const API_ALIAS = "@api";

const HEADER = [
  "# Environment variables this project's modules declare.",
  "# Generated by `saasaloy add`, one entry per declared variable, comments and all.",
  "#",
  "# Copy this file to `.dev.vars` and fill in the blanks: `.dev.vars` is what",
  "# `wrangler dev` reads, and it is gitignored. This example is not — keep it",
  "# checked in, and keep real secrets out of it.",
];

/**
 * Where the file belongs, or undefined when this project has no api workspace yet.
 * The `@api` alias points at the Worker's source directory (`apps/api/src`), so its
 * parent is the workspace root that `wrangler dev` runs in.
 */
export function devVarsExamplePath(
  aliases: Record<string, string>
): string | undefined {
  const src = aliases[API_ALIAS];
  if (!src) {
    return undefined;
  }
  const workspace = posix.dirname(src.replace(/\/+$/, ""));
  if (workspace === "." || workspace === "/") {
    return undefined;
  }
  return posix.join(workspace, DEV_VARS_EXAMPLE);
}

/**
 * The `KEY=value` pairs already in a `.dev.vars.example`. Comments and blank lines are
 * dropped: they are regenerated from the descriptors, which are the current truth about
 * what a variable is for. Only the values a person typed are worth carrying over.
 */
export function parseDevVars(text: string): Record<string, string> {
  const values: Record<string, string> = {};
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const eq = trimmed.indexOf("=");
    if (eq <= 0) {
      continue;
    }
    values[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1);
  }
  return values;
}

export interface RenderDevVarsArgs {
  /** Every variable the installed descriptors declare: name → description. */
  envVars: Record<string, string>;
  /** Local-dev values the descriptors supply for some of them. */
  devVars: Record<string, string>;
  /** Values already in the file, which always win over `devVars`. */
  existing: Record<string, string>;
}

export function renderDevVarsExample(args: RenderDevVarsArgs): string {
  const { envVars, devVars, existing } = args;
  // Everything the file already carried stays, even when no installed module declares
  // it any more — a hand-added variable is not ours to delete.
  const names = [
    ...new Set([...Object.keys(envVars), ...Object.keys(existing)]),
  ].toSorted();

  const blocks = names.map((name) => {
    const value = existing[name] ?? devVars[name] ?? "";
    const description = envVars[name];
    const lines = description
      ? description.split("\n").map((line) => `# ${line}`)
      : ["# Declared outside saasaloy — no module describes this one."];
    lines.push(`${name}=${value}`);
    return lines.join("\n");
  });

  return `${[HEADER.join("\n"), ...blocks].join("\n\n")}\n`;
}

export interface WriteDevVarsArgs extends Omit<RenderDevVarsArgs, "existing"> {
  root: string;
  aliases: Record<string, string>;
}

/**
 * Write (or refresh) the example file. Returns the project-relative path written, or
 * undefined when there is no api workspace or nothing to declare — a project with no
 * environment variables gets no file rather than an empty one.
 */
export async function writeDevVarsExample(
  args: WriteDevVarsArgs
): Promise<string | undefined> {
  const { root, aliases, envVars, devVars } = args;
  const target = devVarsExamplePath(aliases);
  if (!target) {
    return undefined;
  }
  const abs = resolveWithinRoot(root, target);
  const existing = (await pathExists(abs))
    ? parseDevVars(await readFile(abs, "utf-8"))
    : {};
  if (Object.keys(envVars).length === 0 && Object.keys(existing).length === 0) {
    return undefined;
  }
  const content = renderDevVarsExample({ devVars, envVars, existing });
  if ((await pathExists(abs)) && (await readFile(abs, "utf-8")) === content) {
    return undefined;
  }
  await mkdir(dirname(abs), { recursive: true });
  await writeFile(abs, content, "utf-8");
  return target;
}
