import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import {
  assertNoSymlinkPath,
  pathExists,
  resolveWithinRoot,
} from "./fs-utils.js";

// `packages/env/.env.example` — the project's one checked-in key list, generated by
// `saasaloy add` from the installed descriptors' `envVars`. It replaced
// `apps/api/.dev.vars.example`, and with it the per-workspace example: a key two services
// read is now written once, with one comment and one local default.
//
// Three rules keep the regeneration safe:
//
//   1. A value already in the file wins. The file is checked in, so a team edits it, and
//      `saasaloy add` must never revert that edit.
//   2. Nothing is ever removed. `saasaloy remove` owns deletions; an `add` that dropped a
//      key would silently break a second module reading the same variable.
//   3. Every key sits under a `# @services` line. `packages/env` refuses to distribute a
//      key with no section above it, so a key that reaches no service fails the run rather
//      than reaching a Worker that throws on the first request needing it.

/** Where the key list lives, relative to the project root. */
export const ENV_EXAMPLE = "packages/env/.env.example";

/** The literal, case-sensitive prefix that marks a build-time public value. */
export const PUBLIC_PREFIX = "PUBLIC_";

/** The services a project can have. The order here is the order the sections print in. */
export const SERVICE_NAMES = ["api", "web", "admin", "infra"] as const;

export type ServiceName = (typeof SERVICE_NAMES)[number];

/** Services that bundle for a browser, so a `PUBLIC_` key with no declaration goes there. */
const CLIENT_SERVICES: ServiceName[] = ["web", "admin"];

export function isPublicVar(name: string): boolean {
  return name.startsWith(PUBLIC_PREFIX);
}

const HEADER = [
  "# The one key list for this repository. Every `.env` that `pnpm env:setup` writes is",
  "# written from this file. There is no second example file, and no `.dev.vars.example`.",
  "#",
  "# Generated by `saasaloy add` from the installed modules' `envVars`. A value you type",
  "# here survives that, and nothing is ever removed — `saasaloy remove` owns deletions.",
  "#",
  "# `.env` is gitignored; this file is tracked. Keep real secrets out of it.",
  "#",
  "# A `# @services <names>` line sets which services take every key below it, until the",
  "# next such line. A key with no section above it fails `pnpm env:setup`.",
];

/**
 * Which services read `name`, per the declaring module.
 *
 * A descriptor with no `envServices` falls back to the prefix rule alone: a `PUBLIC_` key
 * goes to every client service, everything else to the api. The fallback is what keeps a
 * third-party descriptor written before this field working, and `add` warns when it fires.
 */
export function servicesFor(
  name: string,
  envServices?: Record<string, string[]>
): ServiceName[] {
  const declared = envServices?.[name] ?? envServices?.default;
  if (declared && declared.length > 0) {
    return SERVICE_NAMES.filter((service) => declared.includes(service));
  }
  return isPublicVar(name) ? [...CLIENT_SERVICES] : ["api"];
}

/** What the file already says about one key. */
export interface ExampleEntry {
  value: string;
  /** The comment lines directly above the key, markers included. */
  comment: string[];
  /** The `# @services` line in force above it, when there is one. */
  services: ServiceName[] | undefined;
}

const SECTION = /^\s*#\s*@services\b(.*)$/;

/**
 * Read the example back: each key's value, the comment block above it, and the section it
 * sits under.
 *
 * A module's own wording always replaces the comment on a key it declares — the
 * descriptor is the current truth about what the variable is for. The comment is kept for
 * a key no installed module describes, which is how the base template's own keys survive
 * the first `saasaloy add` with their explanations intact.
 */
export function parseEnvExample(text: string): Record<string, ExampleEntry> {
  const entries: Record<string, ExampleEntry> = {};
  let comment: string[] = [];
  let services: ServiceName[] | undefined;
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    const section = SECTION.exec(trimmed);
    if (section) {
      const named = new Set((section[1] ?? "").split(/[\s,]+/).filter(Boolean));
      services = SERVICE_NAMES.filter((name) => named.has(name));
      comment = [];
      continue;
    }
    if (trimmed.startsWith("#")) {
      comment.push(trimmed);
      continue;
    }
    if (trimmed === "") {
      comment = [];
      continue;
    }
    const eq = trimmed.indexOf("=");
    if (eq <= 0) {
      comment = [];
      continue;
    }
    entries[trimmed.slice(0, eq).trim()] = {
      value: trimmed.slice(eq + 1),
      comment,
      services: services && services.length > 0 ? services : undefined,
    };
    comment = [];
  }
  return entries;
}

export interface RenderExampleArgs {
  /** Every variable the installed descriptors declare: name → description. */
  envVars: Record<string, string>;
  /** Local-dev values the descriptors supply for some of them. */
  devVars: Record<string, string>;
  /** Which services read each key, unioned across the modules that declared it. */
  services: Record<string, ServiceName[]>;
  /** Keys that may stay empty. Each gets a `# Blank on purpose` line above it. */
  optional?: string[];
  /** What the file already says, which always wins over `devVars`. */
  existing: Record<string, ExampleEntry>;
}

/** Sections in a stable order, so a regeneration with no new key is a no-op diff. */
function sectionKey(services: ServiceName[]): string {
  return SERVICE_NAMES.filter((name) => services.includes(name)).join(" ");
}

/** The marker `packages/env`'s `blankOnPurposeKeys` reads. */
export const BLANK_ON_PURPOSE = "# Blank on purpose: this key may stay empty.";

export function renderEnvExample(args: RenderExampleArgs): string {
  const { envVars, devVars, existing } = args;
  const optional = new Set(args.optional);
  // Everything the file already carried stays, even when no installed module declares it
  // any more — a hand-added variable is not ours to delete.
  const names = [
    ...new Set([...Object.keys(envVars), ...Object.keys(existing)]),
  ].toSorted();

  const bySection = new Map<string, string[]>();
  for (const name of names) {
    // A declaring module decides; otherwise the file keeps the section it already had.
    const section = sectionKey(
      args.services[name] ?? existing[name]?.services ?? servicesFor(name)
    );
    bySection.set(section, [...(bySection.get(section) ?? []), name]);
  }

  const blocks: string[] = [];
  for (const section of [...bySection.keys()].toSorted()) {
    blocks.push(`# @services ${section}`);
    for (const name of bySection.get(section) ?? []) {
      const entry = existing[name];
      const value = entry?.value ?? devVars[name] ?? "";
      const description = envVars[name];
      const kept = entry?.comment ?? [];
      const lines = description
        ? description.split("\n").map((line) => `# ${line}`)
        : kept.length > 0
          ? [...kept]
          : ["# Declared outside saasaloy — no module describes this one."];
      // `pnpm env:setup` fails on a key the list carries with no value. A key the
      // declaring module calls optional says so here, which is the one place both the
      // reader and the command look.
      if (optional.has(name)) {
        lines.unshift(BLANK_ON_PURPOSE);
      }
      lines.push(`${name}=${value}`);
      blocks.push(lines.join("\n"));
    }
  }

  return `${[HEADER.join("\n"), ...blocks].join("\n\n")}\n`;
}

export interface WriteExampleArgs extends Omit<RenderExampleArgs, "existing"> {
  root: string;
}

/**
 * Write (or refresh) the key list. Returns the project-relative path written, or
 * undefined when nothing changed and when there is nothing to declare — a project with no
 * environment variables gets no file rather than an empty one.
 */
export async function writeEnvExample(
  args: WriteExampleArgs
): Promise<string | undefined> {
  const { root, envVars, devVars, services, optional } = args;
  const abs = resolveWithinRoot(root, ENV_EXAMPLE);
  // `resolveWithinRoot` proves the path is lexically inside the project; the read and the
  // write below both follow links, so a planted symlink on any component would carry them
  // outside it. Refuse before either, matching `applier` and `remover`.
  await assertNoSymlinkPath(root, abs);
  // One read, reused for the parse and the compare. Reading twice would compare rendered
  // content against a file that may have changed since the values were parsed out of it.
  const before = (await pathExists(abs)) ? await readFile(abs, "utf-8") : "";
  const existing: Record<string, ExampleEntry> = parseEnvExample(before);
  if (Object.keys(envVars).length === 0 && Object.keys(existing).length === 0) {
    return undefined;
  }
  const content = renderEnvExample({
    devVars,
    envVars,
    existing,
    optional,
    services,
  });
  if (before === content) {
    return undefined;
  }
  await mkdir(dirname(abs), { recursive: true });
  await writeFile(abs, content, "utf-8");
  return ENV_EXAMPLE;
}
