import { toDiff } from "./patch/diff.js";
import type {
  ModuleUpdatePlan,
  PlannedUpdateFile,
  PlannedUpdatePatch,
  UpdatePlan,
} from "./updater.js";

// The artifact the whole feature exists for (build spec §2.9, CONTEXT.md): for every
// file `update` refused to overwrite, a structured, agent-consumable merge plan —
// natural-language intent + target files + old/new context — that can be handed
// straight to an agent CLI with no editing. Markdown, because it is the one format
// both a person and an agent read without a renderer (issue #48).
//
// Pure string building: it writes nothing and reads nothing. The command decides
// whether the result goes to stdout or to `--out`.

/** Render the merge plan for everything that drifted, or `""` when nothing did. */
export function renderMergePlan(plan: UpdatePlan): string {
  const modules = plan.modules.filter((m) => m.needsMerge);
  if (modules.length === 0) {
    return "";
  }

  const fileCount = modules.reduce(
    (total, m) =>
      total +
      m.files.filter(isMergeFile).length +
      m.removals.filter(isMergeFile).length,
    0
  );

  const out: string[] = [
    "# Saasaloy merge plan",
    "",
    `Generated by \`saasaloy update\`. ${countLabel(fileCount, "file")} across ` +
      `${countLabel(modules.length, "module")} changed on both sides — upstream and here — so ` +
      "the update stopped short of writing them. Saasaloy never overwrites work you did by " +
      "hand; below is everything needed to reconcile the two sets of changes.",
    "",
  ];

  for (const mod of modules) {
    out.push(...renderModule(mod));
  }

  out.push(...renderInstructions(plan));
  return `${out.join("\n").trimEnd()}\n`;
}

/** Only the states that actually need a human or an agent — the merge plan's whole subject. */
function isMergeFile(file: PlannedUpdateFile): boolean {
  return (
    file.action === "drift" ||
    file.action === "conflict" ||
    file.action === "delete-drift"
  );
}

function countLabel(n: number, noun: string): string {
  return `${n} ${noun}${n === 1 ? "" : "s"}`;
}

function renderModule(mod: ModuleUpdatePlan): string[] {
  const out: string[] = [`## ${mod.name}`, "", "### Intent", ""];

  if (mod.intent.length > 0) {
    out.push(
      "What changed upstream, from the commits touching this module:",
      ""
    );
    for (const subject of mod.intent) {
      out.push(`- ${subject}`);
    }
  } else {
    out.push(
      `No commit subjects could be read for this range${
        mod.noMergeBase ? ` (${mod.noMergeBase})` : ""
      } — read the diffs below to infer what the module intended.`
    );
  }
  out.push(
    "",
    "### Provenance",
    "",
    `- Module: \`${mod.name}\``,
    `- Source: \`${mod.comparison.source}\``,
    `- Ref: \`${mod.comparison.ref}\``,
    `- Base (your version): \`${mod.comparison.current}\``,
    `- Theirs (new version): \`${mod.comparison.latest}\``
  );
  if (mod.noMergeBase) {
    out.push(
      `- **no merge base — ${mod.noMergeBase}**: the original file can't be refetched, so the ` +
        "diffs below are two-way (theirs vs. yours) and you must judge which side each " +
        "difference came from."
    );
  }
  out.push("");

  const mergeFiles = mod.files.filter(isMergeFile);
  const droppedFiles = mod.removals.filter(isMergeFile);
  if (mergeFiles.length > 0 || droppedFiles.length > 0) {
    out.push("### Files to merge", "");
    for (const file of mergeFiles) {
      out.push(...renderFile(file));
    }
    for (const file of droppedFiles) {
      out.push(...renderDroppedFile(file));
    }
  }

  const movedPatches = mod.patches.filter((p) => p.matched !== undefined);
  if (movedPatches.length > 0) {
    out.push(
      "### Config patches that moved",
      "",
      "These config edits were skipped: the key the module identifies its entry by is already " +
        "present, holding a value that isn't the one the new version declares. That is almost " +
        "always a setting you changed on purpose, so nothing was written.",
      ""
    );
    for (const patch of movedPatches) {
      out.push(...renderPatch(patch));
    }
  }

  return out;
}

const ACTION_HEADING: Record<string, string> = {
  drift: "you edited this file after it was applied",
  conflict: "new file collides with yours",
  "delete-drift": "the module dropped this file",
};

function renderFile(file: PlannedUpdateFile): string[] {
  const out: string[] = [
    `#### \`${file.target}\``,
    "",
    `Source in the module: \`${file.from}\` — ${ACTION_HEADING[file.action] ?? file.action}.`,
    "",
  ];

  if (file.action === "conflict") {
    out.push(
      file.base === undefined
        ? "The new version of the module ships this file, but a file already sits at that path " +
            "that Saasaloy never wrote. There is no base for it — the module didn't have it at " +
            "your current version — so this is a two-way comparison."
        : "The new version of the module ships this file, but a file already sits at that path " +
            "that Saasaloy never wrote, so nothing records what it looked like when it was " +
            "applied. The module's own older version of the file is available and is used as " +
            "the base below — but the on-disk file was never tracked against it, so treat it as " +
            "independent work rather than as edits on top of that base.",
      ""
    );
  }

  if (file.patchedBy && file.patchedBy.length > 0) {
    out.push(
      `Note: \`${file.patchedBy.join("`, `")}\` also applied a config patch to this file. Part of ` +
        "the difference below is that patch rather than an edit anyone made by hand — keep those " +
        "lines when you merge.",
      ""
    );
  }

  const base = file.base;
  const theirs = file.theirs ?? "";
  const mine = file.mine ?? "";

  if (base === undefined) {
    out.push(
      "**theirs → mine** (no base available — two-way):",
      "",
      ...fenced(toDiff(theirs, mine, file.target), "diff")
    );
  } else {
    out.push(
      "**base → theirs** (what the module changed):",
      "",
      ...fenced(toDiff(base, theirs, file.target), "diff"),
      "**base → mine** (what you changed):",
      "",
      ...fenced(toDiff(base, mine, file.target), "diff")
    );
  }
  return out;
}

function renderDroppedFile(file: PlannedUpdateFile): string[] {
  const out: string[] = [
    `#### \`${file.target}\``,
    "",
    `Source in the module: \`${file.from}\`. The new version of the module dropped this file, ` +
      "but you had edited it — so it was left exactly as it is and is now yours alone " +
      "(Saasaloy no longer tracks it). Your edits are still here; decide whether the work " +
      "they represent still belongs in the project now the module no longer ships it.",
    "",
  ];
  if (file.base !== undefined && file.mine !== undefined) {
    out.push(
      "**base → mine** (what you changed before it was dropped):",
      "",
      ...fenced(toDiff(file.base, file.mine, file.target), "diff")
    );
  }
  return out;
}

function renderPatch(patch: PlannedUpdatePatch): string[] {
  const matched = patch.matched;
  if (!matched) {
    return [];
  }
  return [
    `#### \`${patch.file}\` — \`${patch.patch.kind}\``,
    "",
    `- Identity: \`${matched.key}\``,
    `- On disk: \`${JSON.stringify(matched.current)}\``,
    `- The new version declares: \`${JSON.stringify(matched.wanted)}\``,
    "",
    "Reconcile these by hand if the new value matters; keep yours if it was deliberate.",
    "",
  ];
}

/**
 * Where the lock is left, said concretely when every merging module shares one base SHA
 * and generically when a bare `update` collected several.
 */
function lockStaysOn(plan: UpdatePlan): string {
  const bases = [
    ...new Set(
      plan.modules.filter((m) => m.needsMerge).map((m) => m.comparison.current)
    ),
  ];
  return bases.length === 1
    ? `the lock stays on \`${bases[0]}\``
    : "each module's lock entry stays on the base SHA named in its Provenance section";
}

function renderInstructions(plan: UpdatePlan): string[] {
  const out: string[] = [
    "## Instructions",
    "",
    "You are reconciling two sets of changes to the same files: the module's (base → theirs) " +
      "and the user's (base → mine). Work file by file.",
    "",
    "1. Read the intent above to understand what the module was trying to fix or add.",
    "2. For each file, apply the module's change to the file **as it currently stands on disk** " +
      "— the on-disk copy is `mine` and it is the version to edit.",
    "3. **The user's edits must not be lost.** Where the two changes touch the same lines, keep " +
      "the user's intent and re-express the module's fix on top of it. If the two genuinely " +
      "conflict and you cannot preserve both, leave the user's version in place and say so " +
      "rather than choosing for them.",
    "4. Don't touch files that aren't listed here — everything else was already updated cleanly.",
    "5. Don't edit `.saasaloy/manifest.json` or `saasaloy-lock.json` — Saasaloy owns both.",
    "",
    "### What Saasaloy records afterwards",
    "",
    "Nothing, and that is deliberate. Saasaloy has no way to tell a finished merge from an " +
      "unfinished one, so it does not mark this plan resolved: the files above stay tracked at " +
      `the module's old version and ${lockStaysOn(plan)}. A later ` +
      "`saasaloy update` will offer the same files again, against the same base, until a file " +
      "either matches the new version byte for byte or the module stops shipping it. The old " +
      "SHA is the only merge base that exists — advancing it would leave these files with " +
      "nothing to diff against, which is why the merge is yours to keep, not Saasaloy's to " +
      "record.",
    "",
    "## Verification",
    "",
    "Run these after merging — `saasaloy update` deliberately runs nothing itself:",
    "",
    `- \`${plan.verifyCommand}\``,
  ];
  if (plan.migrationCommand) {
    out.push(
      `- \`${plan.migrationCommand}\` — the update changed the database schema`
    );
  }
  out.push("");
  return out;
}

/**
 * Wrap content in a fence long enough to survive whatever it contains — a merge plan
 * routinely carries markdown files that hold their own code fences, and a three-backtick
 * fence would end the block early and corrupt the document an agent reads.
 */
function fenced(content: string, language: string): string[] {
  let longest = 0;
  for (const match of content.matchAll(/`{3,}/g)) {
    longest = Math.max(longest, match[0].length);
  }
  const fence = "`".repeat(Math.max(3, longest + 1));
  return [`${fence}${language}`, content.replace(/\n$/, ""), fence, ""];
}
