// Put a README in the tarball npm publishes.
//
// npm reads a package's README from the directory holding its package.json, and nothing
// else. The repo README lives at the root, which is a private package that is never
// published, so saasaloy@0.1.0 shipped with an empty npm page. The `files` array is not
// involved either way: npm always packs a README.md next to the manifest, listed or not.
//
// This copies rather than duplicating by hand, so the npm page and the GitHub front page
// cannot drift. packages/cli/README.md is generated and gitignored; prepack writes it
// before `npm pack` and `npm publish` read it.
//
// The copy is not byte-identical, because relative links do not survive the move. npm
// resolves them against `repository.directory`, which is packages/cli, so `LICENSE.md`
// would point at packages/cli/LICENSE.md and 404. Every relative target is rewritten to an
// absolute github.com URL on the default branch.
//
// Imports nothing but node: builtins. Node 24 strips the types, so there is no build step;
// `pnpm typecheck` checks it via tsconfig.scripts.json.

import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const source = join(root, "README.md");
const target = join(root, "packages/cli/README.md");

/** Where a relative link has to point once the file is read on npm. */
const BLOB_BASE = "https://github.com/mimukit/saasaloy/blob/main/";

/** What to write above the copy, so nobody edits the generated file. */
const BANNER =
  "<!-- Generated by scripts/build-cli-readme.ts from the repo root README.md. Edit that file. -->\n\n";

/**
 * Whether a markdown link target already stands on its own.
 *
 * Absolute URLs, protocol-relative URLs, in-page anchors and mailto: links all resolve the
 * same wherever the file is read. Everything else is relative to the file, which is the
 * only case that breaks when the file moves into packages/cli.
 */
export function isAbsoluteTarget(link: string): boolean {
  return (
    link.startsWith("#") ||
    link.startsWith("//") ||
    /^[a-z][a-z0-9+.-]*:/i.test(link)
  );
}

/**
 * Rewrite every relative markdown link target to an absolute GitHub URL.
 *
 * Inline links only — `[text](target)`. The root README uses no reference definitions and
 * no bare HTML anchors, and a rewriter that guessed at those would be more code than the
 * cases it covers. The tarball assertion in release-smoke.ts is what notices if this stops
 * being true; a missed link renders as text on npm rather than 404ing silently.
 */
export function absolutizeLinks(markdown: string): string {
  return markdown.replaceAll(
    /\[([^\]]*)\]\(([^)\s]+)(\s+"[^"]*")?\)/g,
    (whole, text: string, link: string, title: string | undefined) => {
      if (isAbsoluteTarget(link)) {
        return whole;
      }
      return `[${text}](${BLOB_BASE}${link.replace(/^\.\//, "")}${title ?? ""})`;
    }
  );
}

async function main(): Promise<void> {
  const markdown = await readFile(source, "utf-8");
  await writeFile(target, BANNER + absolutizeLinks(markdown));
  console.log("build-cli-readme: wrote packages/cli/README.md");
}

// Only when run directly, so the test can import the pure functions above.
if (
  process.argv[1] !== undefined &&
  import.meta.filename === resolve(process.argv[1])
) {
  await main();
}
